services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - reader-app
      - writer-app

  reader-app:
    image: eclipse-temurin:21
    volumes:
      - ./jars/reader.jar:/app/app.jar
    command: java -jar /app/app.jar
    depends_on:
      - redis
      - mongodb
  
  writer-app:
    image: eclipse-temurin:21
    volumes:
      - ./jars/writer.jar:/app/app.jar
    command: java -jar /app/app.jar
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: distributed-messager
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d