services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java-app

  java-app:
    image: openjdk:latest
    volumes:
      - ./app:/app
    command: java -jar /app/app.jar
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017